// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaItem struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Platform         string             `json:"platform"`
	Type             string             `json:"type"`
	Title            string             `json:"title"`
	Creator          pgtype.Text        `json:"creator"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	Duration         pgtype.Interval    `json:"duration"`
	TimeSpent        pgtype.Interval    `json:"time_spent"`
	Url              pgtype.Text        `json:"url"`
	ExternalID       string             `json:"external_id"`
	EnrichmentStatus string             `json:"enrichment_status"`
	RawMetadata      []byte             `json:"raw_metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MediaItemTag struct {
	MediaItemID pgtype.UUID        `json:"media_item_id"`
	TagID       pgtype.UUID        `json:"tag_id"`
	Source      string             `json:"source"`
	Confidence  pgtype.Float4      `json:"confidence"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PluginCredential struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Plugin        string             `json:"plugin"`
	AuthType      string             `json:"auth_type"`
	EncryptedData []byte             `json:"encrypted_data"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PluginState struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Plugin       string             `json:"plugin"`
	Status       string             `json:"status"`
	Enabled      bool               `json:"enabled"`
	Cursor       pgtype.Text        `json:"cursor"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SyncLog struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Plugin       string             `json:"plugin"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ItemsAdded   pgtype.Int4        `json:"items_added"`
	ItemsSkipped pgtype.Int4        `json:"items_skipped"`
	ItemsUpdated pgtype.Int4        `json:"items_updated"`
	Status       string             `json:"status"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TagAlias struct {
	ID        pgtype.UUID        `json:"id"`
	Alias     string             `json:"alias"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	AuthProvider string             `json:"auth_provider"`
	AuthSubject  string             `json:"auth_subject"`
	ProfileSlug  pgtype.Text        `json:"profile_slug"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
