// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMediaItemTag = `-- name: AddMediaItemTag :exec
INSERT INTO media_item_tags (media_item_id, tag_id, source, confidence)
VALUES ($1, $2, $3, $4)
ON CONFLICT (media_item_id, tag_id, source) DO UPDATE SET
    confidence = EXCLUDED.confidence
`

type AddMediaItemTagParams struct {
	MediaItemID pgtype.UUID   `json:"media_item_id"`
	TagID       pgtype.UUID   `json:"tag_id"`
	Source      string        `json:"source"`
	Confidence  pgtype.Float4 `json:"confidence"`
}

func (q *Queries) AddMediaItemTag(ctx context.Context, arg AddMediaItemTagParams) error {
	_, err := q.db.Exec(ctx, addMediaItemTag,
		arg.MediaItemID,
		arg.TagID,
		arg.Source,
		arg.Confidence,
	)
	return err
}

const completeSyncLog = `-- name: CompleteSyncLog :one
UPDATE sync_log SET
    completed_at = now(),
    items_added = $2,
    items_skipped = $3,
    items_updated = $4,
    status = $5,
    error_code = $6,
    error_message = $7,
    duration_ms = $8
WHERE id = $1
RETURNING id, user_id, plugin, started_at, completed_at, items_added, items_skipped, items_updated, status, error_code, error_message, duration_ms
`

type CompleteSyncLogParams struct {
	ID           pgtype.UUID `json:"id"`
	ItemsAdded   pgtype.Int4 `json:"items_added"`
	ItemsSkipped pgtype.Int4 `json:"items_skipped"`
	ItemsUpdated pgtype.Int4 `json:"items_updated"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	DurationMs   pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) CompleteSyncLog(ctx context.Context, arg CompleteSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRow(ctx, completeSyncLog,
		arg.ID,
		arg.ItemsAdded,
		arg.ItemsSkipped,
		arg.ItemsUpdated,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ItemsAdded,
		&i.ItemsSkipped,
		&i.ItemsUpdated,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO media_items (user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, raw_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, platform, external_id) DO UPDATE SET
    title = EXCLUDED.title,
    creator = EXCLUDED.creator,
    duration = EXCLUDED.duration,
    time_spent = EXCLUDED.time_spent,
    url = EXCLUDED.url,
    raw_metadata = EXCLUDED.raw_metadata,
    updated_at = now()
RETURNING id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at
`

type CreateMediaItemParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Platform    string             `json:"platform"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Creator     pgtype.Text        `json:"creator"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	Duration    pgtype.Interval    `json:"duration"`
	TimeSpent   pgtype.Interval    `json:"time_spent"`
	Url         pgtype.Text        `json:"url"`
	ExternalID  string             `json:"external_id"`
	RawMetadata []byte             `json:"raw_metadata"`
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, createMediaItem,
		arg.UserID,
		arg.Platform,
		arg.Type,
		arg.Title,
		arg.Creator,
		arg.ConsumedAt,
		arg.Duration,
		arg.TimeSpent,
		arg.Url,
		arg.ExternalID,
		arg.RawMetadata,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Type,
		&i.Title,
		&i.Creator,
		&i.ConsumedAt,
		&i.Duration,
		&i.TimeSpent,
		&i.Url,
		&i.ExternalID,
		&i.EnrichmentStatus,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_log (user_id, plugin)
VALUES ($1, $2)
RETURNING id, user_id, plugin, started_at, completed_at, items_added, items_skipped, items_updated, status, error_code, error_message, duration_ms
`

type CreateSyncLogParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRow(ctx, createSyncLog, arg.UserID, arg.Plugin)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ItemsAdded,
		&i.ItemsSkipped,
		&i.ItemsUpdated,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const createTagAlias = `-- name: CreateTagAlias :one
INSERT INTO tag_aliases (alias, tag_id)
VALUES ($1, $2)
ON CONFLICT (alias) DO NOTHING
RETURNING id, alias, tag_id, created_at
`

type CreateTagAliasParams struct {
	Alias string      `json:"alias"`
	TagID pgtype.UUID `json:"tag_id"`
}

func (q *Queries) CreateTagAlias(ctx context.Context, arg CreateTagAliasParams) (TagAlias, error) {
	row := q.db.QueryRow(ctx, createTagAlias, arg.Alias, arg.TagID)
	var i TagAlias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.TagID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, avatar_url, auth_provider, auth_subject)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	AuthProvider string      `json:"auth_provider"`
	AuthSubject  string      `json:"auth_subject"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.AuthProvider,
		arg.AuthSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePluginCredentials = `-- name: DeletePluginCredentials :exec
DELETE FROM plugin_credentials WHERE user_id = $1 AND plugin = $2
`

type DeletePluginCredentialsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) DeletePluginCredentials(ctx context.Context, arg DeletePluginCredentialsParams) error {
	_, err := q.db.Exec(ctx, deletePluginCredentials, arg.UserID, arg.Plugin)
	return err
}

const getMediaItemByID = `-- name: GetMediaItemByID :one
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at FROM media_items WHERE id = $1 AND user_id = $2
`

type GetMediaItemByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMediaItemByID(ctx context.Context, arg GetMediaItemByIDParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemByID, arg.ID, arg.UserID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Type,
		&i.Title,
		&i.Creator,
		&i.ConsumedAt,
		&i.Duration,
		&i.TimeSpent,
		&i.Url,
		&i.ExternalID,
		&i.EnrichmentStatus,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name, category)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, category, created_at
`

type GetOrCreateTagParams struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) GetOrCreateTag(ctx context.Context, arg GetOrCreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, arg.Name, arg.Category)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getPluginCredentials = `-- name: GetPluginCredentials :one
SELECT id, user_id, plugin, auth_type, encrypted_data, expires_at, created_at, updated_at FROM plugin_credentials WHERE user_id = $1 AND plugin = $2
`

type GetPluginCredentialsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) GetPluginCredentials(ctx context.Context, arg GetPluginCredentialsParams) (PluginCredential, error) {
	row := q.db.QueryRow(ctx, getPluginCredentials, arg.UserID, arg.Plugin)
	var i PluginCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.AuthType,
		&i.EncryptedData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginState = `-- name: GetPluginState :one
SELECT id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at FROM plugin_states WHERE user_id = $1 AND plugin = $2
`

type GetPluginStateParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) GetPluginState(ctx context.Context, arg GetPluginStateParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, getPluginState, arg.UserID, arg.Plugin)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByAlias = `-- name: GetTagByAlias :one
SELECT t.id, t.name, t.category, t.created_at FROM tags t
JOIN tag_aliases ta ON t.id = ta.tag_id
WHERE ta.alias = $1
`

func (q *Queries) GetTagByAlias(ctx context.Context, alias string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByAlias, alias)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, category, created_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAuth = `-- name: GetUserByAuth :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at FROM users WHERE auth_provider = $1 AND auth_subject = $2
`

type GetUserByAuthParams struct {
	AuthProvider string `json:"auth_provider"`
	AuthSubject  string `json:"auth_subject"`
}

func (q *Queries) GetUserByAuth(ctx context.Context, arg GetUserByAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth, arg.AuthProvider, arg.AuthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaItemTags = `-- name: ListMediaItemTags :many
SELECT t.name, t.category, mit.source, mit.confidence
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
WHERE mit.media_item_id = $1
`

type ListMediaItemTagsRow struct {
	Name       string        `json:"name"`
	Category   pgtype.Text   `json:"category"`
	Source     string        `json:"source"`
	Confidence pgtype.Float4 `json:"confidence"`
}

func (q *Queries) ListMediaItemTags(ctx context.Context, mediaItemID pgtype.UUID) ([]ListMediaItemTagsRow, error) {
	rows, err := q.db.Query(ctx, listMediaItemTags, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaItemTagsRow{}
	for rows.Next() {
		var i ListMediaItemTagsRow
		if err := rows.Scan(
			&i.Name,
			&i.Category,
			&i.Source,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaItems = `-- name: ListMediaItems :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
ORDER BY consumed_at DESC
LIMIT $4 OFFSET $5
`

type ListMediaItemsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
}

func (q *Queries) ListMediaItems(ctx context.Context, arg ListMediaItemsParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listMediaItems,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEnrichment = `-- name: ListPendingEnrichment :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at FROM media_items
WHERE enrichment_status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingEnrichment(ctx context.Context, limit int32) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listPendingEnrichment, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginStates = `-- name: ListPluginStates :many
SELECT id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at FROM plugin_states WHERE user_id = $1 ORDER BY plugin
`

func (q *Queries) ListPluginStates(ctx context.Context, userID pgtype.UUID) ([]PluginState, error) {
	rows, err := q.db.Query(ctx, listPluginStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginState{}
	for rows.Next() {
		var i PluginState
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plugin,
			&i.Status,
			&i.Enabled,
			&i.Cursor,
			&i.LastSyncedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncLogs = `-- name: ListSyncLogs :many
SELECT id, user_id, plugin, started_at, completed_at, items_added, items_skipped, items_updated, status, error_code, error_message, duration_ms FROM sync_log
WHERE user_id = $1 AND plugin = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListSyncLogsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListSyncLogs(ctx context.Context, arg ListSyncLogsParams) ([]SyncLog, error) {
	rows, err := q.db.Query(ctx, listSyncLogs, arg.UserID, arg.Plugin, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plugin,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ItemsAdded,
			&i.ItemsSkipped,
			&i.ItemsUpdated,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformBreakdown = `-- name: PlatformBreakdown :many
SELECT platform, type, COUNT(*) AS count,
       SUM(EXTRACT(EPOCH FROM duration))::BIGINT AS total_duration_sec
FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
GROUP BY platform, type
ORDER BY count DESC
`

type PlatformBreakdownParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
}

type PlatformBreakdownRow struct {
	Platform         string `json:"platform"`
	Type             string `json:"type"`
	Count            int64  `json:"count"`
	TotalDurationSec int64  `json:"total_duration_sec"`
}

func (q *Queries) PlatformBreakdown(ctx context.Context, arg PlatformBreakdownParams) ([]PlatformBreakdownRow, error) {
	rows, err := q.db.Query(ctx, platformBreakdown, arg.UserID, arg.ConsumedAt, arg.ConsumedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformBreakdownRow{}
	for rows.Next() {
		var i PlatformBreakdownRow
		if err := rows.Scan(
			&i.Platform,
			&i.Type,
			&i.Count,
			&i.TotalDurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagDistribution = `-- name: TagDistribution :many
SELECT t.name, t.category, COUNT(*) AS count
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
JOIN media_items mi ON mit.media_item_id = mi.id
WHERE mi.user_id = $1
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND (mit.confidence IS NULL OR mit.confidence >= 0.7)
GROUP BY t.name, t.category
ORDER BY count DESC
LIMIT $4
`

type TagDistributionParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
}

type TagDistributionRow struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Count    int64       `json:"count"`
}

func (q *Queries) TagDistribution(ctx context.Context, arg TagDistributionParams) ([]TagDistributionRow, error) {
	rows, err := q.db.Query(ctx, tagDistribution,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagDistributionRow{}
	for rows.Next() {
		var i TagDistributionRow
		if err := rows.Scan(&i.Name, &i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrichmentStatus = `-- name: UpdateEnrichmentStatus :exec
UPDATE media_items SET enrichment_status = $2, updated_at = now()
WHERE id = $1
`

type UpdateEnrichmentStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	EnrichmentStatus string      `json:"enrichment_status"`
}

func (q *Queries) UpdateEnrichmentStatus(ctx context.Context, arg UpdateEnrichmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateEnrichmentStatus, arg.ID, arg.EnrichmentStatus)
	return err
}

const updatePluginStateStatus = `-- name: UpdatePluginStateStatus :one
UPDATE plugin_states SET status = $3, error_message = $4, updated_at = now()
WHERE user_id = $1 AND plugin = $2
RETURNING id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at
`

type UpdatePluginStateStatusParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Plugin       string      `json:"plugin"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdatePluginStateStatus(ctx context.Context, arg UpdatePluginStateStatusParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, updatePluginStateStatus,
		arg.UserID,
		arg.Plugin,
		arg.Status,
		arg.ErrorMessage,
	)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePluginStateSynced = `-- name: UpdatePluginStateSynced :one
UPDATE plugin_states SET
    status = 'connected',
    last_synced_at = now(),
    cursor = $3,
    error_message = NULL,
    updated_at = now()
WHERE user_id = $1 AND plugin = $2
RETURNING id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at
`

type UpdatePluginStateSyncedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
	Cursor pgtype.Text `json:"cursor"`
}

func (q *Queries) UpdatePluginStateSynced(ctx context.Context, arg UpdatePluginStateSyncedParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, updatePluginStateSynced, arg.UserID, arg.Plugin, arg.Cursor)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, avatar_url = $3, profile_slug = $4, updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ProfileSlug pgtype.Text `json:"profile_slug"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.ProfileSlug,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPluginCredentials = `-- name: UpsertPluginCredentials :one
INSERT INTO plugin_credentials (user_id, plugin, auth_type, encrypted_data, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, plugin) DO UPDATE SET
    auth_type = EXCLUDED.auth_type,
    encrypted_data = EXCLUDED.encrypted_data,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING id, user_id, plugin, auth_type, encrypted_data, expires_at, created_at, updated_at
`

type UpsertPluginCredentialsParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	Plugin        string             `json:"plugin"`
	AuthType      string             `json:"auth_type"`
	EncryptedData []byte             `json:"encrypted_data"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertPluginCredentials(ctx context.Context, arg UpsertPluginCredentialsParams) (PluginCredential, error) {
	row := q.db.QueryRow(ctx, upsertPluginCredentials,
		arg.UserID,
		arg.Plugin,
		arg.AuthType,
		arg.EncryptedData,
		arg.ExpiresAt,
	)
	var i PluginCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.AuthType,
		&i.EncryptedData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPluginState = `-- name: UpsertPluginState :one
INSERT INTO plugin_states (user_id, plugin, status, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, plugin) DO UPDATE SET
    status = EXCLUDED.status,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at
`

type UpsertPluginStateParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Plugin  string      `json:"plugin"`
	Status  string      `json:"status"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpsertPluginState(ctx context.Context, arg UpsertPluginStateParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, upsertPluginState,
		arg.UserID,
		arg.Plugin,
		arg.Status,
		arg.Enabled,
	)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
