// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMediaItemTag = `-- name: AddMediaItemTag :exec
INSERT INTO media_item_tags (media_item_id, tag_id, source, confidence)
VALUES ($1, $2, $3, $4)
ON CONFLICT (media_item_id, tag_id, source) DO UPDATE SET
    confidence = EXCLUDED.confidence
`

type AddMediaItemTagParams struct {
	MediaItemID pgtype.UUID   `json:"media_item_id"`
	TagID       pgtype.UUID   `json:"tag_id"`
	Source      string        `json:"source"`
	Confidence  pgtype.Float4 `json:"confidence"`
}

func (q *Queries) AddMediaItemTag(ctx context.Context, arg AddMediaItemTagParams) error {
	_, err := q.db.Exec(ctx, addMediaItemTag,
		arg.MediaItemID,
		arg.TagID,
		arg.Source,
		arg.Confidence,
	)
	return err
}

const attentionByType = `-- name: AttentionByType :many
SELECT type, COUNT(*) AS count,
       COALESCE(SUM(EXTRACT(EPOCH FROM time_spent)), 0)::BIGINT AS total_time_spent_sec,
       COALESCE(SUM(EXTRACT(EPOCH FROM duration)), 0)::BIGINT AS total_duration_sec
FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
    AND ($4::TEXT IS NULL OR platform = $4)
GROUP BY type
ORDER BY total_time_spent_sec DESC
`

type AttentionByTypeParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Platform     pgtype.Text        `json:"platform"`
}

type AttentionByTypeRow struct {
	Type              string `json:"type"`
	Count             int64  `json:"count"`
	TotalTimeSpentSec int64  `json:"total_time_spent_sec"`
	TotalDurationSec  int64  `json:"total_duration_sec"`
}

func (q *Queries) AttentionByType(ctx context.Context, arg AttentionByTypeParams) ([]AttentionByTypeRow, error) {
	rows, err := q.db.Query(ctx, attentionByType,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Platform,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttentionByTypeRow{}
	for rows.Next() {
		var i AttentionByTypeRow
		if err := rows.Scan(
			&i.Type,
			&i.Count,
			&i.TotalTimeSpentSec,
			&i.TotalDurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPendingItems = `-- name: ClaimPendingItems :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items
WHERE enrichment_status = 'pending'
    AND enrichment_retries < $2
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimPendingItemsParams struct {
	Limit             int32 `json:"limit"`
	EnrichmentRetries int32 `json:"enrichment_retries"`
}

func (q *Queries) ClaimPendingItems(ctx context.Context, arg ClaimPendingItemsParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, claimPendingItems, arg.Limit, arg.EnrichmentRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichmentRetries,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeSyncLog = `-- name: CompleteSyncLog :one
UPDATE sync_log SET
    completed_at = now(),
    items_added = $2,
    items_skipped = $3,
    items_updated = $4,
    status = $5,
    error_code = $6,
    error_message = $7,
    duration_ms = $8
WHERE id = $1
RETURNING id, user_id, plugin, started_at, completed_at, items_added, items_skipped, items_updated, status, error_code, error_message, duration_ms
`

type CompleteSyncLogParams struct {
	ID           pgtype.UUID `json:"id"`
	ItemsAdded   pgtype.Int4 `json:"items_added"`
	ItemsSkipped pgtype.Int4 `json:"items_skipped"`
	ItemsUpdated pgtype.Int4 `json:"items_updated"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	DurationMs   pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) CompleteSyncLog(ctx context.Context, arg CompleteSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRow(ctx, completeSyncLog,
		arg.ID,
		arg.ItemsAdded,
		arg.ItemsSkipped,
		arg.ItemsUpdated,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ItemsAdded,
		&i.ItemsSkipped,
		&i.ItemsUpdated,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const consumptionHeatmap = `-- name: ConsumptionHeatmap :many
SELECT
    EXTRACT(DOW FROM consumed_at)::INT AS day_of_week,
    EXTRACT(HOUR FROM consumed_at)::INT AS hour_of_day,
    COUNT(*) AS count
FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
    AND ($4::TEXT IS NULL OR platform = $4)
    AND ($5::TEXT IS NULL OR type = $5)
GROUP BY day_of_week, hour_of_day
ORDER BY day_of_week, hour_of_day
`

type ConsumptionHeatmapParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Platform     pgtype.Text        `json:"platform"`
	MediaType    pgtype.Text        `json:"media_type"`
}

type ConsumptionHeatmapRow struct {
	DayOfWeek int32 `json:"day_of_week"`
	HourOfDay int32 `json:"hour_of_day"`
	Count     int64 `json:"count"`
}

// Returns consumption counts grouped by day-of-week (0=Sun..6=Sat) and
// hour-of-day (0..23) for building a 7×24 rhythm heatmap.
func (q *Queries) ConsumptionHeatmap(ctx context.Context, arg ConsumptionHeatmapParams) ([]ConsumptionHeatmapRow, error) {
	rows, err := q.db.Query(ctx, consumptionHeatmap,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Platform,
		arg.MediaType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsumptionHeatmapRow{}
	for rows.Next() {
		var i ConsumptionHeatmapRow
		if err := rows.Scan(&i.DayOfWeek, &i.HourOfDay, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO media_items (user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, raw_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, platform, external_id) DO UPDATE SET
    title = EXCLUDED.title,
    creator = EXCLUDED.creator,
    duration = EXCLUDED.duration,
    time_spent = EXCLUDED.time_spent,
    url = EXCLUDED.url,
    raw_metadata = EXCLUDED.raw_metadata,
    updated_at = now()
RETURNING id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private
`

type CreateMediaItemParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Platform    string             `json:"platform"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Creator     pgtype.Text        `json:"creator"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	Duration    pgtype.Interval    `json:"duration"`
	TimeSpent   pgtype.Interval    `json:"time_spent"`
	Url         pgtype.Text        `json:"url"`
	ExternalID  string             `json:"external_id"`
	RawMetadata []byte             `json:"raw_metadata"`
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, createMediaItem,
		arg.UserID,
		arg.Platform,
		arg.Type,
		arg.Title,
		arg.Creator,
		arg.ConsumedAt,
		arg.Duration,
		arg.TimeSpent,
		arg.Url,
		arg.ExternalID,
		arg.RawMetadata,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Type,
		&i.Title,
		&i.Creator,
		&i.ConsumedAt,
		&i.Duration,
		&i.TimeSpent,
		&i.Url,
		&i.ExternalID,
		&i.EnrichmentStatus,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichmentRetries,
		&i.Private,
	)
	return i, err
}

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_log (user_id, plugin)
VALUES ($1, $2)
RETURNING id, user_id, plugin, started_at, completed_at, items_added, items_skipped, items_updated, status, error_code, error_message, duration_ms
`

type CreateSyncLogParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRow(ctx, createSyncLog, arg.UserID, arg.Plugin)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ItemsAdded,
		&i.ItemsSkipped,
		&i.ItemsUpdated,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.DurationMs,
	)
	return i, err
}

const createTagAlias = `-- name: CreateTagAlias :one
INSERT INTO tag_aliases (alias, tag_id)
VALUES ($1, $2)
ON CONFLICT (alias) DO NOTHING
RETURNING id, alias, tag_id, created_at
`

type CreateTagAliasParams struct {
	Alias string      `json:"alias"`
	TagID pgtype.UUID `json:"tag_id"`
}

func (q *Queries) CreateTagAlias(ctx context.Context, arg CreateTagAliasParams) (TagAlias, error) {
	row := q.db.QueryRow(ctx, createTagAlias, arg.Alias, arg.TagID)
	var i TagAlias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.TagID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, avatar_url, auth_provider, auth_subject)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	AuthProvider string      `json:"auth_provider"`
	AuthSubject  string      `json:"auth_subject"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.AuthProvider,
		arg.AuthSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (email, display_name, auth_provider, auth_subject, password_hash)
VALUES ($1, $2, 'email', $1, $3)
RETURNING id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded
`

type CreateUserWithPasswordParams struct {
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const deleteMediaItemsByPlatform = `-- name: DeleteMediaItemsByPlatform :execrows
DELETE FROM media_items WHERE user_id = $1 AND platform = $2
`

type DeleteMediaItemsByPlatformParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Platform string      `json:"platform"`
}

func (q *Queries) DeleteMediaItemsByPlatform(ctx context.Context, arg DeleteMediaItemsByPlatformParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMediaItemsByPlatform, arg.UserID, arg.Platform)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePluginCredentials = `-- name: DeletePluginCredentials :exec
DELETE FROM plugin_credentials WHERE user_id = $1 AND plugin = $2
`

type DeletePluginCredentialsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) DeletePluginCredentials(ctx context.Context, arg DeletePluginCredentialsParams) error {
	_, err := q.db.Exec(ctx, deletePluginCredentials, arg.UserID, arg.Plugin)
	return err
}

const deleteSyncLogsByPlugin = `-- name: DeleteSyncLogsByPlugin :exec
DELETE FROM sync_log WHERE user_id = $1 AND plugin = $2
`

type DeleteSyncLogsByPluginParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) DeleteSyncLogsByPlugin(ctx context.Context, arg DeleteSyncLogsByPluginParams) error {
	_, err := q.db.Exec(ctx, deleteSyncLogsByPlugin, arg.UserID, arg.Plugin)
	return err
}

const enrichmentStats = `-- name: EnrichmentStats :one
SELECT
    count(*) FILTER (WHERE enrichment_status = 'pending') AS pending,
    count(*) FILTER (WHERE enrichment_status = 'enriching') AS enriching,
    count(*) FILTER (WHERE enrichment_status = 'enriched') AS enriched,
    count(*) FILTER (WHERE enrichment_status = 'failed') AS failed
FROM media_items
WHERE user_id = $1
`

type EnrichmentStatsRow struct {
	Pending   int64 `json:"pending"`
	Enriching int64 `json:"enriching"`
	Enriched  int64 `json:"enriched"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) EnrichmentStats(ctx context.Context, userID pgtype.UUID) (EnrichmentStatsRow, error) {
	row := q.db.QueryRow(ctx, enrichmentStats, userID)
	var i EnrichmentStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Enriching,
		&i.Enriched,
		&i.Failed,
	)
	return i, err
}

const getMediaItemByExternalID = `-- name: GetMediaItemByExternalID :one
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items WHERE user_id = $1 AND platform = $2 AND external_id = $3
`

type GetMediaItemByExternalIDParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Platform   string      `json:"platform"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) GetMediaItemByExternalID(ctx context.Context, arg GetMediaItemByExternalIDParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemByExternalID, arg.UserID, arg.Platform, arg.ExternalID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Type,
		&i.Title,
		&i.Creator,
		&i.ConsumedAt,
		&i.Duration,
		&i.TimeSpent,
		&i.Url,
		&i.ExternalID,
		&i.EnrichmentStatus,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichmentRetries,
		&i.Private,
	)
	return i, err
}

const getMediaItemByID = `-- name: GetMediaItemByID :one
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items WHERE id = $1 AND user_id = $2
`

type GetMediaItemByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMediaItemByID(ctx context.Context, arg GetMediaItemByIDParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemByID, arg.ID, arg.UserID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Type,
		&i.Title,
		&i.Creator,
		&i.ConsumedAt,
		&i.Duration,
		&i.TimeSpent,
		&i.Url,
		&i.ExternalID,
		&i.EnrichmentStatus,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrichmentRetries,
		&i.Private,
	)
	return i, err
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name, category)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, category, created_at
`

type GetOrCreateTagParams struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) GetOrCreateTag(ctx context.Context, arg GetOrCreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, arg.Name, arg.Category)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getPluginCredentials = `-- name: GetPluginCredentials :one
SELECT id, user_id, plugin, auth_type, encrypted_data, expires_at, created_at, updated_at FROM plugin_credentials WHERE user_id = $1 AND plugin = $2
`

type GetPluginCredentialsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) GetPluginCredentials(ctx context.Context, arg GetPluginCredentialsParams) (PluginCredential, error) {
	row := q.db.QueryRow(ctx, getPluginCredentials, arg.UserID, arg.Plugin)
	var i PluginCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.AuthType,
		&i.EncryptedData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginState = `-- name: GetPluginState :one
SELECT id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at FROM plugin_states WHERE user_id = $1 AND plugin = $2
`

type GetPluginStateParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
}

func (q *Queries) GetPluginState(ctx context.Context, arg GetPluginStateParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, getPluginState, arg.UserID, arg.Plugin)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicItems = `-- name: GetPublicItems :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items
WHERE user_id = $1
    AND private = false
    AND consumed_at >= $2
    AND consumed_at <= $3
    AND ($5::TEXT IS NULL OR platform = $5)
ORDER BY consumed_at DESC
LIMIT $4
`

type GetPublicItemsParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2   pgtype.Timestamptz `json:"consumed_at_2"`
	Limit          int32              `json:"limit"`
	PlatformFilter pgtype.Text        `json:"platform_filter"`
}

func (q *Queries) GetPublicItems(ctx context.Context, arg GetPublicItemsParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, getPublicItems,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.PlatformFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichmentRetries,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicPlatformMix = `-- name: GetPublicPlatformMix :many
SELECT mi.platform, COUNT(*) AS count
FROM media_items mi
WHERE mi.user_id = $1
    AND mi.private = false
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND NOT (mi.platform = ANY($4::TEXT[]))
GROUP BY mi.platform
ORDER BY count DESC
`

type GetPublicPlatformMixParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Column4      []string           `json:"column_4"`
}

type GetPublicPlatformMixRow struct {
	Platform string `json:"platform"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetPublicPlatformMix(ctx context.Context, arg GetPublicPlatformMixParams) ([]GetPublicPlatformMixRow, error) {
	rows, err := q.db.Query(ctx, getPublicPlatformMix,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicPlatformMixRow{}
	for rows.Next() {
		var i GetPublicPlatformMixRow
		if err := rows.Scan(&i.Platform, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicTagDistribution = `-- name: GetPublicTagDistribution :many
SELECT t.name, t.category, COUNT(*) AS count
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
JOIN media_items mi ON mit.media_item_id = mi.id
WHERE mi.user_id = $1
    AND mi.private = false
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND (mit.confidence IS NULL OR mit.confidence >= 0.7)
    AND NOT (mi.platform = ANY($5::TEXT[]))
    AND NOT (t.name = ANY($6::TEXT[]))
    AND ($7::TEXT IS NULL OR t.category = $7)
GROUP BY t.name, t.category
ORDER BY count DESC
LIMIT $4
`

type GetPublicTagDistributionParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2   pgtype.Timestamptz `json:"consumed_at_2"`
	Limit          int32              `json:"limit"`
	Column5        []string           `json:"column_5"`
	Column6        []string           `json:"column_6"`
	CategoryFilter pgtype.Text        `json:"category_filter"`
}

type GetPublicTagDistributionRow struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Count    int64       `json:"count"`
}

func (q *Queries) GetPublicTagDistribution(ctx context.Context, arg GetPublicTagDistributionParams) ([]GetPublicTagDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPublicTagDistribution,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Column5,
		arg.Column6,
		arg.CategoryFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicTagDistributionRow{}
	for rows.Next() {
		var i GetPublicTagDistributionRow
		if err := rows.Scan(&i.Name, &i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicTopCreators = `-- name: GetPublicTopCreators :many
SELECT mi.creator, mi.platform, mi.type, COUNT(*) AS count
FROM media_items mi
WHERE mi.user_id = $1
    AND mi.private = false
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND mi.creator IS NOT NULL AND mi.creator != ''
    AND NOT (mi.platform = ANY($5::TEXT[]))
GROUP BY mi.creator, mi.platform, mi.type
ORDER BY count DESC
LIMIT $4
`

type GetPublicTopCreatorsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
	Column5      []string           `json:"column_5"`
}

type GetPublicTopCreatorsRow struct {
	Creator  pgtype.Text `json:"creator"`
	Platform string      `json:"platform"`
	Type     string      `json:"type"`
	Count    int64       `json:"count"`
}

func (q *Queries) GetPublicTopCreators(ctx context.Context, arg GetPublicTopCreatorsParams) ([]GetPublicTopCreatorsRow, error) {
	rows, err := q.db.Query(ctx, getPublicTopCreators,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicTopCreatorsRow{}
	for rows.Next() {
		var i GetPublicTopCreatorsRow
		if err := rows.Scan(
			&i.Creator,
			&i.Platform,
			&i.Type,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShareProfile = `-- name: GetShareProfile :one

SELECT id, user_id, blocks, excluded_platforms, excluded_tags, published, slug, created_at, updated_at FROM share_profiles WHERE user_id = $1
`

// === Share Profiles ===
func (q *Queries) GetShareProfile(ctx context.Context, userID pgtype.UUID) (ShareProfile, error) {
	row := q.db.QueryRow(ctx, getShareProfile, userID)
	var i ShareProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blocks,
		&i.ExcludedPlatforms,
		&i.ExcludedTags,
		&i.Published,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareProfileBySlug = `-- name: GetShareProfileBySlug :one
SELECT sp.id, sp.user_id, sp.blocks, sp.excluded_platforms, sp.excluded_tags, sp.published, sp.slug, sp.created_at, sp.updated_at, u.display_name, u.avatar_url
FROM share_profiles sp
JOIN users u ON sp.user_id = u.id
WHERE sp.slug = $1 AND sp.published = true
`

type GetShareProfileBySlugRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Blocks            []byte             `json:"blocks"`
	ExcludedPlatforms []string           `json:"excluded_platforms"`
	ExcludedTags      []string           `json:"excluded_tags"`
	Published         bool               `json:"published"`
	Slug              pgtype.Text        `json:"slug"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetShareProfileBySlug(ctx context.Context, slug pgtype.Text) (GetShareProfileBySlugRow, error) {
	row := q.db.QueryRow(ctx, getShareProfileBySlug, slug)
	var i GetShareProfileBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blocks,
		&i.ExcludedPlatforms,
		&i.ExcludedTags,
		&i.Published,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getTagByAlias = `-- name: GetTagByAlias :one
SELECT t.id, t.name, t.category, t.created_at FROM tags t
JOIN tag_aliases ta ON t.id = ta.tag_id
WHERE ta.alias = $1
`

func (q *Queries) GetTagByAlias(ctx context.Context, alias string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByAlias, alias)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, category, created_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAuth = `-- name: GetUserByAuth :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded FROM users WHERE auth_provider = $1 AND auth_subject = $2
`

type GetUserByAuthParams struct {
	AuthProvider string `json:"auth_provider"`
	AuthSubject  string `json:"auth_subject"`
}

func (q *Queries) GetUserByAuth(ctx context.Context, arg GetUserByAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth, arg.AuthProvider, arg.AuthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const getUserByProfileSlug = `-- name: GetUserByProfileSlug :one
SELECT id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded FROM users WHERE profile_slug = $1
`

func (q *Queries) GetUserByProfileSlug(ctx context.Context, profileSlug pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProfileSlug, profileSlug)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const listMediaItemTags = `-- name: ListMediaItemTags :many
SELECT t.name, t.category, mit.source, mit.confidence
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
WHERE mit.media_item_id = $1
`

type ListMediaItemTagsRow struct {
	Name       string        `json:"name"`
	Category   pgtype.Text   `json:"category"`
	Source     string        `json:"source"`
	Confidence pgtype.Float4 `json:"confidence"`
}

func (q *Queries) ListMediaItemTags(ctx context.Context, mediaItemID pgtype.UUID) ([]ListMediaItemTagsRow, error) {
	rows, err := q.db.Query(ctx, listMediaItemTags, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaItemTagsRow{}
	for rows.Next() {
		var i ListMediaItemTagsRow
		if err := rows.Scan(
			&i.Name,
			&i.Category,
			&i.Source,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaItems = `-- name: ListMediaItems :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
ORDER BY consumed_at DESC
LIMIT $4 OFFSET $5
`

type ListMediaItemsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
}

func (q *Queries) ListMediaItems(ctx context.Context, arg ListMediaItemsParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listMediaItems,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichmentRetries,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaItemsFiltered = `-- name: ListMediaItemsFiltered :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
    AND ($6::TEXT IS NULL OR platform = $6)
    AND ($7::TEXT IS NULL OR type = $7)
    AND ($8::TEXT IS NULL OR (
        title ILIKE '%' || $8 || '%'
        OR creator ILIKE '%' || $8 || '%'
    ))
ORDER BY consumed_at DESC
LIMIT $4 OFFSET $5
`

type ListMediaItemsFilteredParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
	Platform     pgtype.Text        `json:"platform"`
	MediaType    pgtype.Text        `json:"media_type"`
	Search       pgtype.Text        `json:"search"`
}

func (q *Queries) ListMediaItemsFiltered(ctx context.Context, arg ListMediaItemsFilteredParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listMediaItemsFiltered,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Offset,
		arg.Platform,
		arg.MediaType,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichmentRetries,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEnrichment = `-- name: ListPendingEnrichment :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items
WHERE enrichment_status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingEnrichment(ctx context.Context, limit int32) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, listPendingEnrichment, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichmentRetries,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginStates = `-- name: ListPluginStates :many
SELECT id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at FROM plugin_states WHERE user_id = $1 ORDER BY plugin
`

func (q *Queries) ListPluginStates(ctx context.Context, userID pgtype.UUID) ([]PluginState, error) {
	rows, err := q.db.Query(ctx, listPluginStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginState{}
	for rows.Next() {
		var i PluginState
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plugin,
			&i.Status,
			&i.Enabled,
			&i.Cursor,
			&i.LastSyncedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncLogs = `-- name: ListSyncLogs :many
SELECT id, user_id, plugin, started_at, completed_at, items_added, items_skipped, items_updated, status, error_code, error_message, duration_ms FROM sync_log
WHERE user_id = $1 AND plugin = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListSyncLogsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListSyncLogs(ctx context.Context, arg ListSyncLogsParams) ([]SyncLog, error) {
	rows, err := q.db.Query(ctx, listSyncLogs, arg.UserID, arg.Plugin, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plugin,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ItemsAdded,
			&i.ItemsSkipped,
			&i.ItemsUpdated,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserOnboarded = `-- name: MarkUserOnboarded :exec
UPDATE users SET onboarded = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkUserOnboarded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserOnboarded, id)
	return err
}

const onThisDay = `-- name: OnThisDay :many
SELECT id, user_id, platform, type, title, creator, consumed_at, duration, time_spent, url, external_id, enrichment_status, raw_metadata, created_at, updated_at, enrichment_retries, private FROM media_items
WHERE user_id = $1
    AND EXTRACT(MONTH FROM consumed_at) = $4::INT
    AND EXTRACT(DAY FROM consumed_at) = $5::INT
    AND consumed_at < $2
ORDER BY consumed_at DESC
LIMIT $3
`

type OnThisDayParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	Limit       int32              `json:"limit"`
	TargetMonth int32              `json:"target_month"`
	TargetDay   int32              `json:"target_day"`
}

func (q *Queries) OnThisDay(ctx context.Context, arg OnThisDayParams) ([]MediaItem, error) {
	rows, err := q.db.Query(ctx, onThisDay,
		arg.UserID,
		arg.ConsumedAt,
		arg.Limit,
		arg.TargetMonth,
		arg.TargetDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaItem{}
	for rows.Next() {
		var i MediaItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Type,
			&i.Title,
			&i.Creator,
			&i.ConsumedAt,
			&i.Duration,
			&i.TimeSpent,
			&i.Url,
			&i.ExternalID,
			&i.EnrichmentStatus,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrichmentRetries,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformBreakdown = `-- name: PlatformBreakdown :many
SELECT platform, type, COUNT(*) AS count,
       COALESCE(SUM(EXTRACT(EPOCH FROM duration)), 0)::BIGINT AS total_duration_sec
FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
GROUP BY platform, type
ORDER BY count DESC
`

type PlatformBreakdownParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
}

type PlatformBreakdownRow struct {
	Platform         string `json:"platform"`
	Type             string `json:"type"`
	Count            int64  `json:"count"`
	TotalDurationSec int64  `json:"total_duration_sec"`
}

func (q *Queries) PlatformBreakdown(ctx context.Context, arg PlatformBreakdownParams) ([]PlatformBreakdownRow, error) {
	rows, err := q.db.Query(ctx, platformBreakdown, arg.UserID, arg.ConsumedAt, arg.ConsumedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformBreakdownRow{}
	for rows.Next() {
		var i PlatformBreakdownRow
		if err := rows.Scan(
			&i.Platform,
			&i.Type,
			&i.Count,
			&i.TotalDurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformBreakdownFiltered = `-- name: PlatformBreakdownFiltered :many
SELECT platform, type, COUNT(*) AS count,
       COALESCE(SUM(EXTRACT(EPOCH FROM duration)), 0)::BIGINT AS total_duration_sec
FROM media_items
WHERE user_id = $1
    AND consumed_at >= $2
    AND consumed_at <= $3
    AND ($4::TEXT IS NULL OR platform = $4)
    AND ($5::TEXT IS NULL OR type = $5)
GROUP BY platform, type
ORDER BY count DESC
`

type PlatformBreakdownFilteredParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Platform     pgtype.Text        `json:"platform"`
	MediaType    pgtype.Text        `json:"media_type"`
}

type PlatformBreakdownFilteredRow struct {
	Platform         string `json:"platform"`
	Type             string `json:"type"`
	Count            int64  `json:"count"`
	TotalDurationSec int64  `json:"total_duration_sec"`
}

func (q *Queries) PlatformBreakdownFiltered(ctx context.Context, arg PlatformBreakdownFilteredParams) ([]PlatformBreakdownFilteredRow, error) {
	rows, err := q.db.Query(ctx, platformBreakdownFiltered,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Platform,
		arg.MediaType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformBreakdownFilteredRow{}
	for rows.Next() {
		var i PlatformBreakdownFilteredRow
		if err := rows.Scan(
			&i.Platform,
			&i.Type,
			&i.Count,
			&i.TotalDurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetEnrichmentByID = `-- name: ResetEnrichmentByID :exec
UPDATE media_items SET
    enrichment_status = 'pending',
    enrichment_retries = 0,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type ResetEnrichmentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ResetEnrichmentByID(ctx context.Context, arg ResetEnrichmentByIDParams) error {
	_, err := q.db.Exec(ctx, resetEnrichmentByID, arg.ID, arg.UserID)
	return err
}

const resetEnrichmentByUser = `-- name: ResetEnrichmentByUser :execrows
UPDATE media_items SET
    enrichment_status = 'pending',
    enrichment_retries = 0,
    updated_at = now()
WHERE user_id = $1
    AND enrichment_status IN ('enriched', 'failed')
`

func (q *Queries) ResetEnrichmentByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetEnrichmentByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemPrivacy = `-- name: SetItemPrivacy :one
UPDATE media_items SET private = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, private
`

type SetItemPrivacyParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Private bool        `json:"private"`
}

type SetItemPrivacyRow struct {
	ID      pgtype.UUID `json:"id"`
	Private bool        `json:"private"`
}

func (q *Queries) SetItemPrivacy(ctx context.Context, arg SetItemPrivacyParams) (SetItemPrivacyRow, error) {
	row := q.db.QueryRow(ctx, setItemPrivacy, arg.ID, arg.UserID, arg.Private)
	var i SetItemPrivacyRow
	err := row.Scan(&i.ID, &i.Private)
	return i, err
}

const tagDistribution = `-- name: TagDistribution :many
SELECT t.name, t.category, COUNT(*) AS count
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
JOIN media_items mi ON mit.media_item_id = mi.id
WHERE mi.user_id = $1
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND (mit.confidence IS NULL OR mit.confidence >= 0.7)
GROUP BY t.name, t.category
ORDER BY count DESC
LIMIT $4
`

type TagDistributionParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
}

type TagDistributionRow struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Count    int64       `json:"count"`
}

func (q *Queries) TagDistribution(ctx context.Context, arg TagDistributionParams) ([]TagDistributionRow, error) {
	rows, err := q.db.Query(ctx, tagDistribution,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagDistributionRow{}
	for rows.Next() {
		var i TagDistributionRow
		if err := rows.Scan(&i.Name, &i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagDistributionByCategory = `-- name: TagDistributionByCategory :many
SELECT t.name, t.category, COUNT(*) AS count
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
JOIN media_items mi ON mit.media_item_id = mi.id
WHERE mi.user_id = $1
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND (mit.confidence IS NULL OR mit.confidence >= 0.7)
    AND ($5::TEXT IS NULL OR mi.platform = $5)
    AND ($6::TEXT IS NULL OR mi.type = $6)
    AND t.category = $7
GROUP BY t.name, t.category
ORDER BY count DESC
LIMIT $4
`

type TagDistributionByCategoryParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
	Platform     pgtype.Text        `json:"platform"`
	MediaType    pgtype.Text        `json:"media_type"`
	Category     pgtype.Text        `json:"category"`
}

type TagDistributionByCategoryRow struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Count    int64       `json:"count"`
}

func (q *Queries) TagDistributionByCategory(ctx context.Context, arg TagDistributionByCategoryParams) ([]TagDistributionByCategoryRow, error) {
	rows, err := q.db.Query(ctx, tagDistributionByCategory,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Platform,
		arg.MediaType,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagDistributionByCategoryRow{}
	for rows.Next() {
		var i TagDistributionByCategoryRow
		if err := rows.Scan(&i.Name, &i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagDistributionFiltered = `-- name: TagDistributionFiltered :many
SELECT t.name, t.category, COUNT(*) AS count
FROM media_item_tags mit
JOIN tags t ON mit.tag_id = t.id
JOIN media_items mi ON mit.media_item_id = mi.id
WHERE mi.user_id = $1
    AND mi.consumed_at >= $2
    AND mi.consumed_at <= $3
    AND (mit.confidence IS NULL OR mit.confidence >= 0.7)
    AND ($5::TEXT IS NULL OR mi.platform = $5)
    AND ($6::TEXT IS NULL OR mi.type = $6)
GROUP BY t.name, t.category
ORDER BY count DESC
LIMIT $4
`

type TagDistributionFilteredParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAt_2 pgtype.Timestamptz `json:"consumed_at_2"`
	Limit        int32              `json:"limit"`
	Platform     pgtype.Text        `json:"platform"`
	MediaType    pgtype.Text        `json:"media_type"`
}

type TagDistributionFilteredRow struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Count    int64       `json:"count"`
}

func (q *Queries) TagDistributionFiltered(ctx context.Context, arg TagDistributionFilteredParams) ([]TagDistributionFilteredRow, error) {
	rows, err := q.db.Query(ctx, tagDistributionFiltered,
		arg.UserID,
		arg.ConsumedAt,
		arg.ConsumedAt_2,
		arg.Limit,
		arg.Platform,
		arg.MediaType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagDistributionFilteredRow{}
	for rows.Next() {
		var i TagDistributionFilteredRow
		if err := rows.Scan(&i.Name, &i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrichmentStatus = `-- name: UpdateEnrichmentStatus :exec
UPDATE media_items SET enrichment_status = $2, updated_at = now()
WHERE id = $1
`

type UpdateEnrichmentStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	EnrichmentStatus string      `json:"enrichment_status"`
}

func (q *Queries) UpdateEnrichmentStatus(ctx context.Context, arg UpdateEnrichmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateEnrichmentStatus, arg.ID, arg.EnrichmentStatus)
	return err
}

const updateEnrichmentStatusWithRetries = `-- name: UpdateEnrichmentStatusWithRetries :exec
UPDATE media_items SET
    enrichment_status = $2,
    enrichment_retries = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateEnrichmentStatusWithRetriesParams struct {
	ID                pgtype.UUID `json:"id"`
	EnrichmentStatus  string      `json:"enrichment_status"`
	EnrichmentRetries int32       `json:"enrichment_retries"`
}

func (q *Queries) UpdateEnrichmentStatusWithRetries(ctx context.Context, arg UpdateEnrichmentStatusWithRetriesParams) error {
	_, err := q.db.Exec(ctx, updateEnrichmentStatusWithRetries, arg.ID, arg.EnrichmentStatus, arg.EnrichmentRetries)
	return err
}

const updatePluginStateStatus = `-- name: UpdatePluginStateStatus :one
UPDATE plugin_states SET status = $3, error_message = $4, updated_at = now()
WHERE user_id = $1 AND plugin = $2
RETURNING id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at
`

type UpdatePluginStateStatusParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Plugin       string      `json:"plugin"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdatePluginStateStatus(ctx context.Context, arg UpdatePluginStateStatusParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, updatePluginStateStatus,
		arg.UserID,
		arg.Plugin,
		arg.Status,
		arg.ErrorMessage,
	)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePluginStateSynced = `-- name: UpdatePluginStateSynced :one
UPDATE plugin_states SET
    status = 'connected',
    last_synced_at = now(),
    cursor = $3,
    error_message = NULL,
    updated_at = now()
WHERE user_id = $1 AND plugin = $2
RETURNING id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at
`

type UpdatePluginStateSyncedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Plugin string      `json:"plugin"`
	Cursor pgtype.Text `json:"cursor"`
}

func (q *Queries) UpdatePluginStateSynced(ctx context.Context, arg UpdatePluginStateSyncedParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, updatePluginStateSynced, arg.UserID, arg.Plugin, arg.Cursor)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, avatar_url = $3, profile_slug = $4, updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, avatar_url, auth_provider, auth_subject, profile_slug, created_at, updated_at, password_hash, onboarded
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ProfileSlug pgtype.Text `json:"profile_slug"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.ProfileSlug,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.ProfileSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Onboarded,
	)
	return i, err
}

const upsertPluginCredentials = `-- name: UpsertPluginCredentials :one
INSERT INTO plugin_credentials (user_id, plugin, auth_type, encrypted_data, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, plugin) DO UPDATE SET
    auth_type = EXCLUDED.auth_type,
    encrypted_data = EXCLUDED.encrypted_data,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
RETURNING id, user_id, plugin, auth_type, encrypted_data, expires_at, created_at, updated_at
`

type UpsertPluginCredentialsParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	Plugin        string             `json:"plugin"`
	AuthType      string             `json:"auth_type"`
	EncryptedData []byte             `json:"encrypted_data"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertPluginCredentials(ctx context.Context, arg UpsertPluginCredentialsParams) (PluginCredential, error) {
	row := q.db.QueryRow(ctx, upsertPluginCredentials,
		arg.UserID,
		arg.Plugin,
		arg.AuthType,
		arg.EncryptedData,
		arg.ExpiresAt,
	)
	var i PluginCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.AuthType,
		&i.EncryptedData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPluginState = `-- name: UpsertPluginState :one
INSERT INTO plugin_states (user_id, plugin, status, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, plugin) DO UPDATE SET
    status = EXCLUDED.status,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, user_id, plugin, status, enabled, cursor, last_synced_at, error_message, created_at, updated_at
`

type UpsertPluginStateParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Plugin  string      `json:"plugin"`
	Status  string      `json:"status"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpsertPluginState(ctx context.Context, arg UpsertPluginStateParams) (PluginState, error) {
	row := q.db.QueryRow(ctx, upsertPluginState,
		arg.UserID,
		arg.Plugin,
		arg.Status,
		arg.Enabled,
	)
	var i PluginState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plugin,
		&i.Status,
		&i.Enabled,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertShareProfile = `-- name: UpsertShareProfile :one
INSERT INTO share_profiles (user_id, blocks, excluded_platforms, excluded_tags, published, slug)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    blocks = EXCLUDED.blocks,
    excluded_platforms = EXCLUDED.excluded_platforms,
    excluded_tags = EXCLUDED.excluded_tags,
    published = EXCLUDED.published,
    slug = EXCLUDED.slug,
    updated_at = now()
RETURNING id, user_id, blocks, excluded_platforms, excluded_tags, published, slug, created_at, updated_at
`

type UpsertShareProfileParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	Blocks            []byte      `json:"blocks"`
	ExcludedPlatforms []string    `json:"excluded_platforms"`
	ExcludedTags      []string    `json:"excluded_tags"`
	Published         bool        `json:"published"`
	Slug              pgtype.Text `json:"slug"`
}

func (q *Queries) UpsertShareProfile(ctx context.Context, arg UpsertShareProfileParams) (ShareProfile, error) {
	row := q.db.QueryRow(ctx, upsertShareProfile,
		arg.UserID,
		arg.Blocks,
		arg.ExcludedPlatforms,
		arg.ExcludedTags,
		arg.Published,
		arg.Slug,
	)
	var i ShareProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Blocks,
		&i.ExcludedPlatforms,
		&i.ExcludedTags,
		&i.Published,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
